# Generated by Django 5.2.16 on 2026-07-26 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120, verbose_name='公司')),
                ('role', models.CharField(max_length=120, verbose_name='岗位')),
                ('status', models.CharField(choices=[('saved', '待投递'), ('applied', '已投递'), ('assessment', '笔试'), ('interview', '面试'), ('offer', 'Offer'), ('closed', '已结束')], default='saved', max_length=20, verbose_name='进度')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级')),
                ('work_mode', models.CharField(choices=[('onsite', '现场'), ('hybrid', '混合'), ('remote', '远程')], default='onsite', max_length=10, verbose_name='工作方式')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='地点')),
                ('source_url', models.URLField(blank=True, verbose_name='职位链接')),
                ('salary_text', models.CharField(blank=True, max_length=80, verbose_name='薪资')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('applied_at', models.DateField(blank=True, null=True, verbose_name='投递日期')),
                ('job_description', models.TextField(blank=True, verbose_name='职位描述')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '投递记录',
                'verbose_name_plural': '投递记录',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('saved', '待投递'), ('applied', '已投递'), ('assessment', '笔试'), ('interview', '面试'), ('offer', 'Offer'), ('closed', '已结束')], max_length=20, verbose_name='原进度')),
                ('to_status', models.CharField(choices=[('saved', '待投递'), ('applied', '已投递'), ('assessment', '笔试'), ('interview', '面试'), ('offer', 'Offer'), ('closed', '已结束')], max_length=20, verbose_name='新进度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='jobs.jobapplication', verbose_name='投递记录')),
            ],
            options={
                'verbose_name': '进度变更',
                'verbose_name_plural': '进度变更',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'status'], name='jobs_jobapp_user_id_149a27_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'deadline'], name='jobs_jobapp_user_id_76bc9c_idx'),
        ),
    ]
