# Generated by Django 5.2.16 on 2026-07-26 18:33

import django.db.models.deletion
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='面试时间'),
        ),
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=jobs.models.resume_upload_path, verbose_name='简历文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='文件类型')),
                ('extracted_text', models.TextField(blank=True, verbose_name='提取文本')),
                ('analysis', models.JSONField(blank=True, default=dict, verbose_name='分析结果')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '简历档案',
                'verbose_name_plural': '简历档案',
            },
        ),
        migrations.CreateModel(
            name='InterviewPrepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('position', '岗位重点'), ('project', '项目复盘'), ('resume', '简历表达'), ('fundamental', '基础知识'), ('story', '行为面试')], max_length=20, verbose_name='分类')),
                ('title', models.CharField(max_length=220, verbose_name='复习项')),
                ('detail', models.CharField(blank=True, max_length=500, verbose_name='复习建议')),
                ('is_done', models.BooleanField(default=False, verbose_name='已完成')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_items', to='jobs.jobapplication', verbose_name='投递记录')),
            ],
            options={
                'verbose_name': '面试复习项',
                'verbose_name_plural': '面试复习项',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('application', 'title'), name='unique_prep_item_per_application')],
            },
        ),
    ]
